#include <SDL.h>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <cmath>
#include <cfloat>
#include <string>
#include <vector>
#include <thread>
#include <mutex>
#include <deque>
#include <atomic>
#include <chrono>
#include <memory>
#include <climits>
#include <algorithm>
#include <cctype>
#include <strings.h>

#include "imgui.h"
#include "backends/imgui_impl_sdl2.h"
#include "backends/imgui_impl_opengl3.h"

#include "qrcodegen/qrcodegen.h"

#include "env.h"
#include "http_client.h"
#include "api_client.h"
#include "rfid_client.h"

// Generated by the Makefile from VERSION + the current git commit (see
// build/version.h and the APP_VERSION rule in Makefile).
#include "version.h"

#ifdef __APPLE__
#include <OpenGL/gl3.h>
#else
// Raspberry Pi's Mesa V3D driver hands out EGL configs that only support
// GLES rendering, not desktop GL — requesting a desktop Core context (even
// as low as 3.0) fails EGL config matching outright (EGL_BAD_MATCH).
// GLES2 is what's reliably available there. IMGUI_IMPL_OPENGL_ES2 (set in
// Makefile) switches imgui's OpenGL3 backend to its GLES2-compatible path.
#include <SDL_opengles2.h>
#endif

// Directory containing the running executable, so config files like .env
// are found next to the binary regardless of the process's working
// directory (e.g. when launched from an IDE/debugger instead of a shell).
static std::string GetExecutableDir(const char* argv0)
{
    char resolved[PATH_MAX];
    if (realpath(argv0, resolved) != nullptr)
    {
        std::string full(resolved);
        size_t slash = full.find_last_of('/');
        if (slash != std::string::npos)
            return full.substr(0, slash);
    }
    return ".";
}

// How long (in seconds) a check-in code stays valid before rotating.
// Used both as the offline-demo cadence and as the initial progress-bar
// scale before the first real /totp response tells us the server's period.
static const double kCodeLifetimeSeconds = 10.0;

static const char* kAppVersion = APP_VERSION;

// Shown only if the API is unreachable at startup, so the kiosk still demos.
static const std::vector<ScheduleEntry> kFallbackSchedule = {
    { "08:00 - 09:15", "Data Structures",         "Room 214" },
    { "09:30 - 10:45", "Linear Algebra",           "Room 118" },
    { "11:00 - 12:15", "Computer Networks",        "Room 302" },
    { "13:30 - 14:45", "Operating Systems",        "Room 214" },
    { "15:00 - 16:15", "Software Engineering Lab", "Lab 4"    },
};

// Generates a short, human-friendly attendance code (no ambiguous chars).
// Used only as an offline fallback when the API's TOTP endpoint is unavailable.
static std::string GenerateAttendanceCode()
{
    static const char charset[] = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
    static const size_t charsetLen = sizeof(charset) - 1;

    std::string code;
    for (int i = 0; i < 6; i++)
        code += charset[rand() % charsetLen];
    return code;
}

// Builds the check-in deep link the QR code encodes. Falls back to the bare
// code (old behavior) when there's no frontend URL configured or no real
// session to check into (offline demo mode).
static std::string BuildCheckInQrText(const std::string& frontendUrl, int classSessionId, const std::string& code)
{
    if (frontendUrl.empty() || classSessionId < 0)
        return code;
    return frontendUrl + "checkin?class=" + std::to_string(classSessionId) + "&code=" + code;
}

static void RegenerateQr(const std::string& text, uint8_t tempBuffer[], uint8_t qrcode[])
{
    qrcodegen_encodeText(
        text.c_str(),
        tempBuffer,
        qrcode,
        qrcodegen_Ecc_MEDIUM,
        qrcodegen_VERSION_MIN,
        qrcodegen_VERSION_MAX,
        qrcodegen_Mask_AUTO,
        true
    );
}

// Parses a ScheduleEntry::time string ("HH:MM - HH:MM") into minutes since
// midnight. Returns false for placeholder values like "TBD".
static bool ParseTimeRangeMinutes(const std::string& range, int& outStartMinutes, int& outEndMinutes)
{
    int startHour, startMin, endHour, endMin;
    if (sscanf(range.c_str(), "%d:%d - %d:%d", &startHour, &startMin, &endHour, &endMin) != 4)
        return false;
    outStartMinutes = startHour * 60 + startMin;
    outEndMinutes = endHour * 60 + endMin;
    return true;
}

// Normally the wall-clock time, but overridable via ATTENDANCE_DEBUG_TIME
// ("HH:MM") so the current-class highlight can be tested without waiting
// for a real class to start.
static int CurrentMinutesOfDay()
{
    static const std::string debugTime = dotenv::Get("ATTENDANCE_DEBUG_TIME");
    int debugHour, debugMin;
    if (!debugTime.empty() && sscanf(debugTime.c_str(), "%d:%d", &debugHour, &debugMin) == 2)
        return debugHour * 60 + debugMin;

    std::time_t t = std::time(nullptr);
    std::tm local;
    localtime_r(&t, &local);
    return local.tm_hour * 60 + local.tm_min;
}

// Today's calendar date for the footer, e.g. "Fri, Sep 4". Always the real
// date -- ATTENDANCE_DEBUG_TIME (see CurrentMinutesOfDay) only overrides
// the time-of-day, not the date.
static std::string FormatFooterDate()
{
    std::time_t t = std::time(nullptr);
    std::tm local;
    localtime_r(&t, &local);
    char buf[32];
    strftime(buf, sizeof(buf), "%a, %b %d", &local);
    return buf;
}

// The clock shown in the footer, e.g. "2:05 PM". Built from
// CurrentMinutesOfDay() so it reflects ATTENDANCE_DEBUG_TIME when set --
// handy for confirming the footer and the current-class highlight agree
// on what time it "is".
static std::string FormatFooterTime()
{
    int minutes = CurrentMinutesOfDay();
    int hour24 = (minutes / 60) % 24;
    int minute = minutes % 60;
    const char* suffix = hour24 < 12 ? "AM" : "PM";
    int hour12 = hour24 % 12;
    if (hour12 == 0)
        hour12 = 12;
    char buf[16];
    snprintf(buf, sizeof(buf), "%d:%02d %s", hour12, minute, suffix);
    return buf;
}

// Looks for "Sprint <N>" in a class name (e.g. "BIT370 ... (Sprint 2)") and
// returns N, or -1 if the name doesn't mention a sprint at all.
static int ExtractSprintNumber(const std::string& course)
{
    for (size_t i = 0; i + 6 <= course.size(); i++)
    {
        if (strncasecmp(course.c_str() + i, "Sprint", 6) == 0)
        {
            size_t j = i + 6;
            while (j < course.size() && isspace((unsigned char)course[j]))
                j++;
            if (j < course.size() && isdigit((unsigned char)course[j]))
                return atoi(course.c_str() + j);
        }
    }
    return -1;
}

// Drops schedule rows for other sprints, per ATTENDANCE_SPRINT ("1" or "2").
// A class whose name doesn't mention "Sprint" at all is left in either way.
static void FilterScheduleBySprint(std::vector<ScheduleEntry>& schedule)
{
    std::string sprintFilter = dotenv::Get("ATTENDANCE_SPRINT");
    if (sprintFilter.empty())
        return;

    int wantSprint = atoi(sprintFilter.c_str());
    schedule.erase(
        std::remove_if(schedule.begin(), schedule.end(), [wantSprint](const ScheduleEntry& entry) {
            int sprint = ExtractSprintNumber(entry.course);
            return sprint != -1 && sprint != wantSprint;
        }),
        schedule.end());
}

// Draws a QR code (with quiet zone) at originScreenPos, each module moduleSize pixels wide.
static void DrawQrCode(ImDrawList* drawList, ImVec2 originScreenPos, const uint8_t qrcode[], float moduleSize)
{
    const int size = qrcodegen_getSize(qrcode);
    const int border = 4;
    const ImU32 white = IM_COL32(255, 255, 255, 255);
    const ImU32 black = IM_COL32(0, 0, 0, 255);

    const float total = (float)(size + border * 2) * moduleSize;
    drawList->AddRectFilled(originScreenPos, ImVec2(originScreenPos.x + total, originScreenPos.y + total), white);

    for (int y = 0; y < size; y++)
    {
        for (int x = 0; x < size; x++)
        {
            if (qrcodegen_getModule(qrcode, x, y))
            {
                ImVec2 p0(originScreenPos.x + (x + border) * moduleSize, originScreenPos.y + (y + border) * moduleSize);
                ImVec2 p1(p0.x + moduleSize, p0.y + moduleSize);
                drawList->AddRectFilled(p0, p1, black);
            }
        }
    }
}

// Polls GET /api/ClassSessions/{id}/totp on a background thread so a slow
// or hung network call never blocks a render frame (this is a kiosk display
// that must keep animating smoothly regardless of backend latency).
class TotpPoller
{
public:
    TotpPoller(ApiClient& client, int sessionId)
        : client_(client), sessionId_(sessionId), thread_(&TotpPoller::Run, this)
    {
    }

    ~TotpPoller()
    {
        stop_.store(true);
        if (thread_.joinable())
            thread_.join();
    }

    // True once at least one successful response has been received.
    bool HasData()
    {
        std::lock_guard<std::mutex> lock(mutex_);
        return haveData_;
    }

    // Returns the latest known code, and the seconds remaining extrapolated
    // forward from when it was fetched to "now".
    void GetLatest(std::string& outCode, double& outSecondsRemaining, double& outPeriodSeconds)
    {
        std::lock_guard<std::mutex> lock(mutex_);
        outCode = code_;
        outPeriodSeconds = periodSeconds_;

        double elapsed = std::chrono::duration<double>(std::chrono::steady_clock::now() - fetchedAt_).count();
        outSecondsRemaining = secondsRemainingAtFetch_ - elapsed;
        if (outSecondsRemaining < 0.0)
            outSecondsRemaining = 0.0;
    }

private:
    void Run()
    {
        while (!stop_.load())
        {
            TotpInfo info;
            if (client_.FetchTotp(sessionId_, info))
            {
                std::lock_guard<std::mutex> lock(mutex_);

                if (info.code != code_)
                {
                    code_ = info.code;
                    periodSeconds_ = info.secondsRemaining > 0 ? (double)info.secondsRemaining : kCodeLifetimeSeconds;
                }

                secondsRemainingAtFetch_ = (double)info.secondsRemaining;
                fetchedAt_ = std::chrono::steady_clock::now();
                haveData_ = true;
            }

            for (int i = 0; i < 10 && !stop_.load(); i++)
                std::this_thread::sleep_for(std::chrono::milliseconds(100));
        }
    }

    ApiClient& client_;
    int sessionId_;
    std::thread thread_;
    std::atomic<bool> stop_{false};

    std::mutex mutex_;
    bool haveData_ = false;
    std::string code_;
    double periodSeconds_ = kCodeLifetimeSeconds;
    double secondsRemainingAtFetch_ = 0.0;
    std::chrono::steady_clock::time_point fetchedAt_;
};

// Broad display bucket for one auto-checkin attempt, driving both the
// status line's text and its color.
enum class NfcCheckInOutcome
{
    CheckedIn,        // new attendance record
    AlreadyCheckedIn, // record already existed
    Error,            // any failure (see NfcCheckInEvent::statusText for which)
};

// Outcome of one auto-checkin attempt, for the main thread to display.
struct NfcCheckInEvent
{
    NfcCheckInOutcome outcome = NfcCheckInOutcome::Error;
    std::string studentName; // empty for errors -- the server never resolves
                              // a student on a failure path (see AutoCheckIn)
    std::string statusText;  // e.g. "Checked in to BIT370", "No class to check-in"
};

// Turns the auto-checkin endpoint's `{ "error": "<Code>", "message": "..." }`
// body into a short label for the status line. Known codes as of writing
// (NoClassRunning, ScheduleConflict, UnrecognizedBadge, NotEnrolled) get a
// terse, kiosk-friendly label; anything else (a code we don't know about
// yet, or no code at all -- e.g. a transport error) falls back to the
// server's own message so a new failure mode is never silently blank.
static std::string DescribeAutoCheckInError(const std::string& errorCode, const std::string& errorMessage)
{
    if (errorCode == "NoClassRunning")
        return "No class to check-in";
    if (errorCode == "ScheduleConflict")
        return "Schedule conflict in this room";
    if (errorCode == "UnrecognizedBadge")
        return "Card not recognized";
    if (errorCode == "NotEnrolled")
        return "Not enrolled in this class";
    return !errorMessage.empty() ? errorMessage : "Check-in failed";
}

// Watches the Python RFID server (see rfid_client.h) on a background
// thread -- waiting for a "card" event is itself blocking, and so is the
// POST /api/ClassSessions/auto-checkin it triggers, so neither should run
// on the render thread. Taps that arrive faster than the main thread
// displays them queue up instead of overwriting each other, so a run of
// students tapping in quick succession each still get their own few
// seconds on screen.
class NfcCheckInWorker
{
public:
    NfcCheckInWorker(ApiClient& client, std::string rfidSocketPath)
        : client_(client), rfid_(std::move(rfidSocketPath)), thread_(&NfcCheckInWorker::Run, this)
    {
    }

    ~NfcCheckInWorker()
    {
        stop_.store(true);
        rfid_.Stop(); // unblocks a WaitForCard() the thread may be sitting in
        if (thread_.joinable())
            thread_.join();
    }

    // Pops the oldest queued event, if any.
    bool PopEvent(NfcCheckInEvent& outEvent)
    {
        std::lock_guard<std::mutex> lock(mutex_);
        if (queue_.empty())
            return false;
        outEvent = std::move(queue_.front());
        queue_.pop_front();
        return true;
    }

private:
    void Run()
    {
        while (!stop_.load())
        {
            std::vector<uint8_t> uid;
            if (!rfid_.WaitForCard(uid))
                break; // Stop() was called

            AutoCheckInResult result;
            std::string errorCode, errorMessage;
            NfcCheckInEvent event;

            if (client_.AutoCheckIn(uid, result, errorCode, errorMessage))
            {
                event.studentName = result.studentFirstName + " " + result.studentLastName;
                if (result.alreadyCheckedIn)
                {
                    event.outcome = NfcCheckInOutcome::AlreadyCheckedIn;
                    event.statusText = "Already checked in to " + result.className;
                }
                else
                {
                    event.outcome = NfcCheckInOutcome::CheckedIn;
                    event.statusText = "Checked in to " + result.className;
                }
            }
            else
            {
                event.outcome = NfcCheckInOutcome::Error;
                event.statusText = DescribeAutoCheckInError(errorCode, errorMessage);
            }

            std::lock_guard<std::mutex> lock(mutex_);
            queue_.push_back(std::move(event));
        }
    }

    ApiClient& client_;
    RfidSocketClient rfid_;
    std::thread thread_;
    std::atomic<bool> stop_{false};

    std::mutex mutex_;
    std::deque<NfcCheckInEvent> queue_;
};

int main(int argc, char* argv[])
{
    setvbuf(stdout, nullptr, _IOLBF, 0); // flush log lines promptly, e.g. under `tail -f`

    srand((unsigned int)time(nullptr));

    dotenv::Load(GetExecutableDir(argv[0]) + "/.env");
    HttpGlobalInit();

    // --- API setup -------------------------------------------------------
    std::string apiUrl = dotenv::Get("ATTENDANCE_API_URL", "http://localhost:5261/");
    ApiClient apiClient(apiUrl);
    apiClient.Authenticate();

    // The QR code encodes a deep link into the student-facing check-in page,
    // not just the bare code, so a phone camera can jump straight there.
    std::string frontendUrl = dotenv::Get("ATTENDANCE_FRONTEND_URL");
    if (!frontendUrl.empty() && frontendUrl.back() != '/')
        frontendUrl += '/';

    std::string configuredRoom = dotenv::Get("ATTENDANCE_ROOM");
    std::vector<ScheduleEntry> schedule;
    int classSessionId = -1;
    bool useRemoteTotp = false;

    if (apiClient.IsEndpointAuth())
    {
        // Device (X-Api-Key) auth: room is implicit in the key's server-side
        // claim, so no ATTENDANCE_ROOM/ResolveRoomId lookup is needed here.
        if (apiClient.FetchScheduleForEndpoint(schedule) && !schedule.empty())
        {
            // Not every class has a session yet (e.g. none created for
            // today) — try each until one resolves, not just the first.
            for (const ScheduleEntry& entry : schedule)
            {
                if (apiClient.ResolveSessionIdForClass(entry.classId, classSessionId))
                {
                    useRemoteTotp = true;
                    break;
                }
            }
            if (!useRemoteTotp)
                printf("Attendance API: none of this room's classes have a session yet; showing schedule only.\n");
        }
        else
        {
            schedule = kFallbackSchedule;
        }
    }
    else
    {
        // User (JWT) auth: a kiosk is physically mounted in one room, so this
        // scopes every fetch below to just that room's classes/sessions
        // instead of showing every class in the building.
        int roomId = -1;
        if (!configuredRoom.empty() && !apiClient.ResolveRoomId(configuredRoom, roomId))
            printf("Attendance API: could not resolve ATTENDANCE_ROOM=\"%s\" to a room id; showing all rooms.\n", configuredRoom.c_str());

        if (!apiClient.FetchSchedule(schedule, roomId) || schedule.empty())
            schedule = kFallbackSchedule;

        useRemoteTotp = apiClient.ResolveClassSessionId(classSessionId, roomId);
    }

    FilterScheduleBySprint(schedule);

    // Room label for the footer bar: prefer the configured room (works
    // under endpoint auth too, since ATTENDANCE_ROOM is just read from the
    // environment regardless of auth mode), falling back to whatever room
    // the fetched schedule says.
    std::string roomLabel = configuredRoom;
    if (roomLabel.empty() && !schedule.empty() && schedule[0].room != "No room")
        roomLabel = schedule[0].room;
    if (roomLabel.empty())
        roomLabel = "—";

    if (!apiClient.IsReachable())
        printf("Attendance API at %s is unreachable; showing offline demo data.\n", apiUrl.c_str());

    // Auto-checkin (NFC tap, read by rfid-py/rfid_server.py and relayed to
    // us over a Unix socket -- see rfid_client.h) is only meaningful under
    // endpoint (device) auth: the server resolves both the student and the
    // class session from the card UID plus the endpoint's own room/key, so
    // there's no session to pick under user auth anyway. NfcCheckInWorker
    // degrades gracefully (retries quietly in the background) if the
    // Python server isn't running or hasn't started yet.
    std::unique_ptr<NfcCheckInWorker> nfcWorker;
    if (apiClient.IsEndpointAuth())
    {
        std::string rfidSocketPath = dotenv::Get("ATTENDANCE_RFID_SOCKET", "/tmp/rfid.sock");
        nfcWorker.reset(new NfcCheckInWorker(apiClient, rfidSocketPath));
    }

    // Initialize SDL
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER | SDL_INIT_GAMECONTROLLER) != 0)
    {
        printf("SDL_Init failed: %s\n", SDL_GetError());
        return 1;
    }

#ifdef __APPLE__
    // OpenGL 3.2 Core + GLSL 150: macOS refuses to give out anything above
    // legacy GL 2.1 unless you request exactly a forward-compatible Core
    // context like this.
    const char* glsl_version = "#version 150";
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS, SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);
#else
    // OpenGL ES 2.0 + GLSL ES 100: Raspberry Pi's Mesa V3D driver only
    // reliably hands out GLES-capable EGL configs, not desktop-GL-capable
    // ones — requesting any desktop Core profile (3.2, 3.0, ...) fails EGL
    // config matching outright (EGL_BAD_MATCH), regardless of version.
    const char* glsl_version = "#version 100";
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS, 0);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
#endif

    // Create window
    SDL_Window* window = SDL_CreateWindow(
        "Attendance",
        SDL_WINDOWPOS_CENTERED,
        SDL_WINDOWPOS_CENTERED,
        1024,
        600,
        SDL_WINDOW_OPENGL |
        SDL_WINDOW_RESIZABLE |
        SDL_WINDOW_ALLOW_HIGHDPI
    );

    if (!window)
    {
        printf("SDL_CreateWindow failed: %s\n", SDL_GetError());
        SDL_Quit();
        return 1;
    }

    // Nothing on screen is clickable (see README) -- hide the mouse cursor
    // so it doesn't sit visibly over the kiosk display.
    SDL_ShowCursor(SDL_DISABLE);

    // Create OpenGL context
    SDL_GLContext gl_context = SDL_GL_CreateContext(window);

    if (!gl_context)
    {
        printf("SDL_GL_CreateContext failed: %s\n", SDL_GetError());
        SDL_DestroyWindow(window);
        SDL_Quit();
        return 1;
    }

    SDL_GL_MakeCurrent(window, gl_context);
    SDL_GL_SetSwapInterval(1);

    // Print GPU information
    printf("Vendor:   %s\n", glGetString(GL_VENDOR));
    printf("Renderer: %s\n", glGetString(GL_RENDERER));
    printf("Version:  %s\n", glGetString(GL_VERSION));

    // Initialize Dear ImGui
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();

    ImGuiIO& io = ImGui::GetIO();
    (void)io;

    // Without this, ImGui_ImplSDL2_NewFrame() re-enables the OS cursor every
    // frame (it manages cursor visibility/shape itself by default), which
    // undoes the SDL_ShowCursor(SDL_DISABLE) below on the very next frame.
    io.ConfigFlags |= ImGuiConfigFlags_NoMouseCursorChange;

    ImGui::StyleColorsDark();

    // Initialize ImGui SDL2 + OpenGL3 backends
    ImGui_ImplSDL2_InitForOpenGL(window, gl_context);
    if (!ImGui_ImplOpenGL3_Init(glsl_version))
    {
        printf("ImGui_ImplOpenGL3_Init failed (see \"Failed to initialize OpenGL loader!\" above "
               "if printed) - GL version/loader mismatch. Try `make clean && make`.\n");
        ImGui_ImplSDL2_Shutdown();
        ImGui::DestroyContext();
        SDL_GL_DeleteContext(gl_context);
        SDL_DestroyWindow(window);
        SDL_Quit();
        return 1;
    }

    bool running = true;

    // Offline-demo rotation state.
    double totalTime = 0.0;
    int lastCycleIndex = -1;

    // Live /totp rotation state: fetched on a background thread (see
    // TotpPoller) so a slow network never stalls rendering.
    double totpPeriodSeconds = kCodeLifetimeSeconds;

    std::unique_ptr<TotpPoller> totpPoller;
    if (useRemoteTotp)
        totpPoller.reset(new TotpPoller(apiClient, classSessionId));

    std::string currentCode = "......";
    uint8_t qrTempBuffer[qrcodegen_BUFFER_LEN_MAX];
    uint8_t qrCode[qrcodegen_BUFFER_LEN_MAX];
    RegenerateQr(BuildCheckInQrText(frontendUrl, classSessionId, currentCode), qrTempBuffer, qrCode);

    // Currently displayed NFC auto-checkin result, shown below the QR code
    // for a few seconds before the next queued tap (if any) takes its
    // place. hasNfcStatus tracks whether nfcStatus is "live" separately
    // from whether it's empty, so a still-displaying event with an empty
    // studentName (an error) doesn't read as "nothing to show".
    NfcCheckInEvent nfcStatus;
    bool hasNfcStatus = false;
    double nfcStatusUntil = 0.0;

    while (running)
    {
        SDL_Event event;

        while (SDL_PollEvent(&event))
        {
            ImGui_ImplSDL2_ProcessEvent(&event);

            if (event.type == SDL_QUIT)
                running = false;

            if (event.type == SDL_WINDOWEVENT &&
                event.window.event == SDL_WINDOWEVENT_CLOSE)
            {
                running = false;
            }
        }

        // Start ImGui frame
        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplSDL2_NewFrame();
        ImGui::NewFrame();

        // Once the current status has had its 5 seconds, advance to the
        // next queued tap (if any) instead of just clearing -- this is what
        // makes a run of back-to-back taps display one at a time rather
        // than the later ones silently overwriting the earlier ones.
        if (!hasNfcStatus || ImGui::GetTime() >= nfcStatusUntil)
        {
            hasNfcStatus = nfcWorker && nfcWorker->PopEvent(nfcStatus);
            if (hasNfcStatus)
                nfcStatusUntil = ImGui::GetTime() + 5.0;
        }

        // Advance the rotating check-in code countdown.
        double secondsRemaining;

        if (useRemoteTotp)
        {
            if (totpPoller->HasData())
            {
                std::string latestCode;
                double latestSecondsRemaining;
                totpPoller->GetLatest(latestCode, latestSecondsRemaining, totpPeriodSeconds);

                if (latestCode != currentCode)
                {
                    currentCode = latestCode;
                    RegenerateQr(BuildCheckInQrText(frontendUrl, classSessionId, currentCode), qrTempBuffer, qrCode);
                }

                secondsRemaining = latestSecondsRemaining;
            }
            else
            {
                // No response yet (first frame or a network hiccup): keep
                // showing the placeholder rather than blocking.
                secondsRemaining = 0.0;
            }
        }
        else
        {
            totalTime += io.DeltaTime;

            const int cycleIndex = (int)(totalTime / kCodeLifetimeSeconds);
            const double secondsIntoCycle = totalTime - cycleIndex * kCodeLifetimeSeconds;
            secondsRemaining = kCodeLifetimeSeconds - secondsIntoCycle;
            totpPeriodSeconds = kCodeLifetimeSeconds;

            if (cycleIndex != lastCycleIndex)
            {
                lastCycleIndex = cycleIndex;
                currentCode = GenerateAttendanceCode();
                RegenerateQr(BuildCheckInQrText(frontendUrl, classSessionId, currentCode), qrTempBuffer, qrCode);
            }
        }

        // Fullscreen, static kiosk window: no title bar, no resize/move handles, nothing clickable.
        ImGui::SetNextWindowPos(ImVec2(0, 0));
        ImGui::SetNextWindowSize(io.DisplaySize);

        ImGuiWindowFlags windowFlags =
            ImGuiWindowFlags_NoTitleBar |
            ImGuiWindowFlags_NoResize |
            ImGuiWindowFlags_NoMove |
            ImGuiWindowFlags_NoCollapse |
            ImGuiWindowFlags_NoSavedSettings |
            ImGuiWindowFlags_NoScrollbar;

        ImGui::Begin("Attendance", nullptr, windowFlags);

        // Header bar: app name on the left, version on the right.
        {
            char rightLabel[32];
            snprintf(rightLabel, sizeof(rightLabel), "v%s", kAppVersion);

            ImGui::TextUnformatted("Attendance Tool");
            ImGui::SameLine();

            float rightWidth = ImGui::CalcTextSize(rightLabel).x;
            ImGui::SetCursorPosX(ImGui::GetContentRegionMax().x - rightWidth);
            ImGui::TextDisabled("%s", rightLabel);
        }
        ImGui::Separator();
        ImGui::Spacing();

        // Reserve room at the bottom for the footer bar (separator +
        // spacing + one text line) before sizing the two main panels, since
        // the footer is drawn after them but must not be squeezed out.
        const float footerHeight = ImGui::GetTextLineHeightWithSpacing() + ImGui::GetStyle().ItemSpacing.y + 8.0f;
        const float panelHeight = ImGui::GetContentRegionAvail().y - footerHeight;

        // Left panel: today's schedule.
        ImGui::BeginChild("SchedulePanel", ImVec2(ImGui::GetContentRegionAvail().x * 0.55f, panelHeight), true, ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoInputs);

        ImGui::TextUnformatted("Today's Schedule");
        ImGui::Separator();
        ImGui::Spacing();

        // Bigger, more spread-out rows so a handful of classes still fill a
        // fullscreen kiosk panel instead of leaving most of it blank. Room
        // isn't shown per-row either: the kiosk is already scoped to one
        // room, so every row would just repeat the same value.
        const float scheduleFontScale = 1.3f;
        const float timeColumnWidth = 160.0f * scheduleFontScale;

        const int nowMinutes = CurrentMinutesOfDay();
        ImDrawList* scheduleDrawList = ImGui::GetWindowDrawList();
        ImDrawListSplitter scheduleSplitter;
        scheduleSplitter.Split(scheduleDrawList, 2);

        ImGui::SetWindowFontScale(scheduleFontScale);
        for (const ScheduleEntry& item : schedule)
        {
            int startMinutes, endMinutes;
            const bool isCurrent = ParseTimeRangeMinutes(item.time, startMinutes, endMinutes)
                && nowMinutes >= startMinutes && nowMinutes < endMinutes;

            const ImVec2 rowStart = ImGui::GetCursorScreenPos();
            const float rowWidth = ImGui::GetContentRegionAvail().x;

            scheduleSplitter.SetCurrentChannel(scheduleDrawList, 1);
            if (isCurrent)
                ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(0.6f, 1.0f, 0.7f, 1.0f));

            ImGui::TextUnformatted(item.time.c_str());
            ImGui::SameLine(timeColumnWidth);
            ImGui::TextWrapped("%s", item.course.c_str());

            if (isCurrent)
                ImGui::PopStyleColor();

            ImGui::Spacing();
            ImGui::Spacing();
            ImGui::Spacing();

            if (isCurrent)
            {
                const ImVec2 rowEnd(rowStart.x + rowWidth, ImGui::GetCursorScreenPos().y);
                scheduleSplitter.SetCurrentChannel(scheduleDrawList, 0);
                scheduleDrawList->AddRectFilled(rowStart, rowEnd, IM_COL32(46, 125, 90, 120), 4.0f);
            }
        }
        scheduleSplitter.Merge(scheduleDrawList);
        ImGui::SetWindowFontScale(1.0f);

        ImGui::EndChild();

        ImGui::SameLine();

        // Right panel: rotating check-in QR code, code text, and countdown bar.
        ImGui::BeginChild("CheckInPanel", ImVec2(0, panelHeight), true, ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoInputs);

        ImGui::TextUnformatted("Scan to Check In");
        ImGui::SameLine();
        if (useRemoteTotp)
            ImGui::TextDisabled("(live)");
        else
            ImGui::TextDisabled("(offline demo)");
        ImGui::Separator();
        ImGui::Spacing();

        const float availWidth = ImGui::GetContentRegionAvail().x;
        const float availHeight = ImGui::GetContentRegionAvail().y;

        const float codeFontScale = 2.4f;
        const float progressBarHeight = 32.0f;
        const float smallSpacing = 12.0f;
        const float bigSpacing = 24.0f;

        ImGui::SetWindowFontScale(codeFontScale);
        const float codeTextHeight = ImGui::GetTextLineHeight();
        ImGui::SetWindowFontScale(1.0f);

        // Room for the NFC auto-checkin status (student name + status line)
        // below the countdown bar. Reserved whenever a reader was
        // configured at all (endpoint auth), whether or not something is
        // currently displayed there, so the QR/code/bar block above doesn't
        // shift as taps come and go.
        const float nfcAreaHeight = nfcWorker ? (bigSpacing + 2.0f * ImGui::GetTextLineHeight()) : 0.0f;

        // Size the QR to use as much of the panel as it can, reserving just
        // enough room below it for the code text, countdown bar, and NFC status.
        const float reservedHeight = smallSpacing + codeTextHeight + bigSpacing + progressBarHeight + nfcAreaHeight;
        float qrBudget = std::min(availWidth * 0.9f, availHeight - reservedHeight);
        if (qrBudget < 50.0f)
            qrBudget = 50.0f;

        const int qrModules = qrcodegen_getSize(qrCode) + 8; // + quiet zone border
        float moduleSize = qrBudget / (float)qrModules;
        if (moduleSize < 2.0f)
            moduleSize = 2.0f;

        const float qrPixelSize = moduleSize * (float)qrModules;
        const float blockHeight = qrPixelSize + reservedHeight;
        const float verticalOffset = (availHeight - blockHeight) * 0.5f;
        if (verticalOffset > 0.0f)
            ImGui::SetCursorPosY(ImGui::GetCursorPosY() + verticalOffset);

        const float qrOffsetX = (availWidth - qrPixelSize) * 0.5f;
        if (qrOffsetX > 0.0f)
            ImGui::SetCursorPosX(ImGui::GetCursorPosX() + qrOffsetX);

        ImVec2 qrScreenPos = ImGui::GetCursorScreenPos();
        DrawQrCode(ImGui::GetWindowDrawList(), qrScreenPos, qrCode, moduleSize);
        ImGui::Dummy(ImVec2(qrPixelSize, qrPixelSize));

        ImGui::Spacing();

        // Centered, enlarged code text.
        {
            ImGui::SetWindowFontScale(codeFontScale);
            float textWidth = ImGui::CalcTextSize(currentCode.c_str()).x;
            float offsetX = (availWidth - textWidth) * 0.5f;
            if (offsetX > 0.0f)
                ImGui::SetCursorPosX(ImGui::GetCursorPosX() + offsetX);
            ImGui::TextUnformatted(currentCode.c_str());
            ImGui::SetWindowFontScale(1.0f);
        }

        ImGui::Spacing();
        ImGui::Spacing();

        // Countdown bar: full when the code just rotated, empty at 0.
        char overlay[32];
        snprintf(overlay, sizeof(overlay), "%d s", (int)ceil(secondsRemaining));
        float fraction = totpPeriodSeconds > 0.0 ? (float)(secondsRemaining / totpPeriodSeconds) : 0.0f;
        if (fraction < 0.0f) fraction = 0.0f;
        if (fraction > 1.0f) fraction = 1.0f;
        ImGui::ProgressBar(fraction, ImVec2(-FLT_MIN, progressBarHeight), overlay);

        // NFC auto-checkin status: student name plus a colored status line
        // (green = new check-in, yellow = already checked in, red = error),
        // shown for a few seconds per tap and queued behind it (see
        // NfcCheckInWorker) if students tap in quick succession.
        if (nfcWorker)
        {
            ImGui::Spacing();
            ImGui::Spacing();

            if (hasNfcStatus)
            {
                ImVec4 color = nfcStatus.outcome == NfcCheckInOutcome::CheckedIn ? ImVec4(0.6f, 1.0f, 0.7f, 1.0f)
                    : nfcStatus.outcome == NfcCheckInOutcome::AlreadyCheckedIn ? ImVec4(1.0f, 0.9f, 0.5f, 1.0f)
                    : ImVec4(1.0f, 0.55f, 0.5f, 1.0f);

                const std::string& nameLine = nfcStatus.studentName.empty() ? std::string("\xE2\x80\x94") : nfcStatus.studentName;

                float nameWidth = ImGui::CalcTextSize(nameLine.c_str()).x;
                ImGui::SetCursorPosX(ImGui::GetCursorPosX() + std::max(0.0f, (availWidth - nameWidth) * 0.5f));
                ImGui::TextUnformatted(nameLine.c_str());

                float statusWidth = ImGui::CalcTextSize(nfcStatus.statusText.c_str()).x;
                ImGui::SetCursorPosX(ImGui::GetCursorPosX() + std::max(0.0f, (availWidth - statusWidth) * 0.5f));
                ImGui::PushStyleColor(ImGuiCol_Text, color);
                ImGui::TextUnformatted(nfcStatus.statusText.c_str());
                ImGui::PopStyleColor();
            }
            else
            {
                ImGui::Dummy(ImVec2(1.0f, 2.0f * ImGui::GetTextLineHeight()));
            }
        }

        ImGui::EndChild();

        // Footer bar: date + time on the left, room on the right.
        ImGui::Separator();
        {
            std::string leftLabel = FormatFooterDate() + "   " + FormatFooterTime();
            std::string rightLabel = "Room " + roomLabel;

            ImGui::TextUnformatted(leftLabel.c_str());
            ImGui::SameLine();

            float rightWidth = ImGui::CalcTextSize(rightLabel.c_str()).x;
            ImGui::SetCursorPosX(ImGui::GetContentRegionMax().x - rightWidth);
            ImGui::TextUnformatted(rightLabel.c_str());
        }

        ImGui::End();

        // Render
        ImGui::Render();

        int width;
        int height;

        SDL_GL_GetDrawableSize(window, &width, &height);

        glViewport(0, 0, width, height);

        glClearColor(
            0.05f,
            0.05f,
            0.08f,
            1.0f
        );

        glClear(GL_COLOR_BUFFER_BIT);

        ImGui_ImplOpenGL3_RenderDrawData(
            ImGui::GetDrawData()
        );

        SDL_GL_SwapWindow(window);
    }

    // Cleanup
    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplSDL2_Shutdown();
    ImGui::DestroyContext();

    SDL_GL_DeleteContext(gl_context);
    SDL_DestroyWindow(window);
    SDL_Quit();

    HttpGlobalCleanup();

    return 0;
}
