#include <SDL.h>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <cmath>
#include <cfloat>
#include <string>
#include <vector>
#include <thread>
#include <mutex>
#include <atomic>
#include <chrono>
#include <memory>
#include <climits>

#include "imgui.h"
#include "backends/imgui_impl_sdl2.h"
#include "backends/imgui_impl_opengl3.h"

#include "qrcodegen/qrcodegen.h"

#include "env.h"
#include "http_client.h"
#include "api_client.h"

// Generated by the Makefile from VERSION + the current git commit (see
// build/version.h and the APP_VERSION rule in Makefile).
#include "version.h"

#ifdef __APPLE__
#include <OpenGL/gl3.h>
#else
#include <GL/gl3.h>
#endif

// Directory containing the running executable, so config files like .env
// are found next to the binary regardless of the process's working
// directory (e.g. when launched from an IDE/debugger instead of a shell).
static std::string GetExecutableDir(const char* argv0)
{
    char resolved[PATH_MAX];
    if (realpath(argv0, resolved) != nullptr)
    {
        std::string full(resolved);
        size_t slash = full.find_last_of('/');
        if (slash != std::string::npos)
            return full.substr(0, slash);
    }
    return ".";
}

// How long (in seconds) a check-in code stays valid before rotating.
// Used both as the offline-demo cadence and as the initial progress-bar
// scale before the first real /totp response tells us the server's period.
static const double kCodeLifetimeSeconds = 10.0;

static const char* kAppVersion = APP_VERSION;

// Shown only if the API is unreachable at startup, so the kiosk still demos.
static const std::vector<ScheduleEntry> kFallbackSchedule = {
    { "08:00 - 09:15", "Data Structures",         "Room 214" },
    { "09:30 - 10:45", "Linear Algebra",           "Room 118" },
    { "11:00 - 12:15", "Computer Networks",        "Room 302" },
    { "13:30 - 14:45", "Operating Systems",        "Room 214" },
    { "15:00 - 16:15", "Software Engineering Lab", "Lab 4"    },
};

// Generates a short, human-friendly attendance code (no ambiguous chars).
// Used only as an offline fallback when the API's TOTP endpoint is unavailable.
static std::string GenerateAttendanceCode()
{
    static const char charset[] = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
    static const size_t charsetLen = sizeof(charset) - 1;

    std::string code;
    for (int i = 0; i < 6; i++)
        code += charset[rand() % charsetLen];
    return code;
}

static void RegenerateQr(const std::string& text, uint8_t tempBuffer[], uint8_t qrcode[])
{
    qrcodegen_encodeText(
        text.c_str(),
        tempBuffer,
        qrcode,
        qrcodegen_Ecc_MEDIUM,
        qrcodegen_VERSION_MIN,
        qrcodegen_VERSION_MAX,
        qrcodegen_Mask_AUTO,
        true
    );
}

// Draws a QR code (with quiet zone) at originScreenPos, each module moduleSize pixels wide.
static void DrawQrCode(ImDrawList* drawList, ImVec2 originScreenPos, const uint8_t qrcode[], float moduleSize)
{
    const int size = qrcodegen_getSize(qrcode);
    const int border = 4;
    const ImU32 white = IM_COL32(255, 255, 255, 255);
    const ImU32 black = IM_COL32(0, 0, 0, 255);

    const float total = (float)(size + border * 2) * moduleSize;
    drawList->AddRectFilled(originScreenPos, ImVec2(originScreenPos.x + total, originScreenPos.y + total), white);

    for (int y = 0; y < size; y++)
    {
        for (int x = 0; x < size; x++)
        {
            if (qrcodegen_getModule(qrcode, x, y))
            {
                ImVec2 p0(originScreenPos.x + (x + border) * moduleSize, originScreenPos.y + (y + border) * moduleSize);
                ImVec2 p1(p0.x + moduleSize, p0.y + moduleSize);
                drawList->AddRectFilled(p0, p1, black);
            }
        }
    }
}

// Polls GET /api/ClassSessions/{id}/totp on a background thread so a slow
// or hung network call never blocks a render frame (this is a kiosk display
// that must keep animating smoothly regardless of backend latency).
class TotpPoller
{
public:
    TotpPoller(ApiClient& client, int sessionId)
        : client_(client), sessionId_(sessionId), thread_(&TotpPoller::Run, this)
    {
    }

    ~TotpPoller()
    {
        stop_.store(true);
        if (thread_.joinable())
            thread_.join();
    }

    // True once at least one successful response has been received.
    bool HasData()
    {
        std::lock_guard<std::mutex> lock(mutex_);
        return haveData_;
    }

    // Returns the latest known code, and the seconds remaining extrapolated
    // forward from when it was fetched to "now".
    void GetLatest(std::string& outCode, double& outSecondsRemaining, double& outPeriodSeconds)
    {
        std::lock_guard<std::mutex> lock(mutex_);
        outCode = code_;
        outPeriodSeconds = periodSeconds_;

        double elapsed = std::chrono::duration<double>(std::chrono::steady_clock::now() - fetchedAt_).count();
        outSecondsRemaining = secondsRemainingAtFetch_ - elapsed;
        if (outSecondsRemaining < 0.0)
            outSecondsRemaining = 0.0;
    }

private:
    void Run()
    {
        while (!stop_.load())
        {
            TotpInfo info;
            if (client_.FetchTotp(sessionId_, info))
            {
                std::lock_guard<std::mutex> lock(mutex_);

                if (info.code != code_)
                {
                    code_ = info.code;
                    periodSeconds_ = info.secondsRemaining > 0 ? (double)info.secondsRemaining : kCodeLifetimeSeconds;
                }

                secondsRemainingAtFetch_ = (double)info.secondsRemaining;
                fetchedAt_ = std::chrono::steady_clock::now();
                haveData_ = true;
            }

            for (int i = 0; i < 10 && !stop_.load(); i++)
                std::this_thread::sleep_for(std::chrono::milliseconds(100));
        }
    }

    ApiClient& client_;
    int sessionId_;
    std::thread thread_;
    std::atomic<bool> stop_{false};

    std::mutex mutex_;
    bool haveData_ = false;
    std::string code_;
    double periodSeconds_ = kCodeLifetimeSeconds;
    double secondsRemainingAtFetch_ = 0.0;
    std::chrono::steady_clock::time_point fetchedAt_;
};

int main(int argc, char* argv[])
{
    srand((unsigned int)time(nullptr));

    dotenv::Load(GetExecutableDir(argv[0]) + "/.env");
    HttpGlobalInit();

    // --- API setup -------------------------------------------------------
    std::string apiUrl = dotenv::Get("ATTENDANCE_API_URL", "http://localhost:5261/");
    ApiClient apiClient(apiUrl);
    apiClient.Authenticate();

    std::string configuredRoom = dotenv::Get("ATTENDANCE_ROOM");
    std::vector<ScheduleEntry> schedule;
    int classSessionId = -1;
    bool useRemoteTotp = false;

    if (apiClient.IsEndpointAuth())
    {
        // Device (X-Api-Key) auth: room is implicit in the key's server-side
        // claim, so no ATTENDANCE_ROOM/ResolveRoomId lookup is needed here.
        if (apiClient.FetchScheduleForEndpoint(schedule) && !schedule.empty())
        {
            useRemoteTotp = apiClient.ResolveSessionIdForClass(schedule[0].classId, classSessionId);
            if (!useRemoteTotp)
                printf("Attendance API: this endpoint key can't resolve a class session yet "
                       "(GET /api/ClassSessions may not accept endpoint auth); showing schedule only.\n");
        }
        else
        {
            schedule = kFallbackSchedule;
        }
    }
    else
    {
        // User (JWT) auth: a kiosk is physically mounted in one room, so this
        // scopes every fetch below to just that room's classes/sessions
        // instead of showing every class in the building.
        int roomId = -1;
        if (!configuredRoom.empty() && !apiClient.ResolveRoomId(configuredRoom, roomId))
            printf("Attendance API: could not resolve ATTENDANCE_ROOM=\"%s\" to a room id; showing all rooms.\n", configuredRoom.c_str());

        if (!apiClient.FetchSchedule(schedule, roomId) || schedule.empty())
            schedule = kFallbackSchedule;

        useRemoteTotp = apiClient.ResolveClassSessionId(classSessionId, roomId);
    }

    if (!apiClient.IsReachable())
        printf("Attendance API at %s is unreachable; showing offline demo data.\n", apiUrl.c_str());

    std::string headerRoom = configuredRoom.empty()
        ? (schedule.empty() ? "—" : schedule[0].room)
        : configuredRoom;

    // Initialize SDL
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER | SDL_INIT_GAMECONTROLLER) != 0)
    {
        printf("SDL_Init failed: %s\n", SDL_GetError());
        return 1;
    }

    // OpenGL 3.2 Core Profile on macOS
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS, 0);
    SDL_GL_SetAttribute(
        SDL_GL_CONTEXT_PROFILE_MASK,
        SDL_GL_CONTEXT_PROFILE_CORE
    );
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);

    // Create window
    SDL_Window* window = SDL_CreateWindow(
        "Attendance",
        SDL_WINDOWPOS_CENTERED,
        SDL_WINDOWPOS_CENTERED,
        1024,
        600,
        SDL_WINDOW_OPENGL |
        SDL_WINDOW_RESIZABLE |
        SDL_WINDOW_ALLOW_HIGHDPI
    );

    if (!window)
    {
        printf("SDL_CreateWindow failed: %s\n", SDL_GetError());
        SDL_Quit();
        return 1;
    }

    // Create OpenGL context
    SDL_GLContext gl_context = SDL_GL_CreateContext(window);

    if (!gl_context)
    {
        printf("SDL_GL_CreateContext failed: %s\n", SDL_GetError());
        SDL_DestroyWindow(window);
        SDL_Quit();
        return 1;
    }

    SDL_GL_MakeCurrent(window, gl_context);
    SDL_GL_SetSwapInterval(1);

    // Print GPU information
    printf("Vendor:   %s\n", glGetString(GL_VENDOR));
    printf("Renderer: %s\n", glGetString(GL_RENDERER));
    printf("Version:  %s\n", glGetString(GL_VERSION));

    // Initialize Dear ImGui
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();

    ImGuiIO& io = ImGui::GetIO();
    (void)io;

    ImGui::StyleColorsDark();

    // Initialize ImGui SDL2 + OpenGL3 backends
    ImGui_ImplSDL2_InitForOpenGL(window, gl_context);
    ImGui_ImplOpenGL3_Init("#version 150");

    bool running = true;

    // Offline-demo rotation state.
    double totalTime = 0.0;
    int lastCycleIndex = -1;

    // Live /totp rotation state: fetched on a background thread (see
    // TotpPoller) so a slow network never stalls rendering.
    double totpPeriodSeconds = kCodeLifetimeSeconds;

    std::unique_ptr<TotpPoller> totpPoller;
    if (useRemoteTotp)
        totpPoller.reset(new TotpPoller(apiClient, classSessionId));

    std::string currentCode = "......";
    uint8_t qrTempBuffer[qrcodegen_BUFFER_LEN_MAX];
    uint8_t qrCode[qrcodegen_BUFFER_LEN_MAX];
    RegenerateQr(currentCode, qrTempBuffer, qrCode);

    while (running)
    {
        SDL_Event event;

        while (SDL_PollEvent(&event))
        {
            ImGui_ImplSDL2_ProcessEvent(&event);

            if (event.type == SDL_QUIT)
                running = false;

            if (event.type == SDL_WINDOWEVENT &&
                event.window.event == SDL_WINDOWEVENT_CLOSE)
            {
                running = false;
            }
        }

        // Start ImGui frame
        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplSDL2_NewFrame();
        ImGui::NewFrame();

        // Advance the rotating check-in code countdown.
        double secondsRemaining;

        if (useRemoteTotp)
        {
            if (totpPoller->HasData())
            {
                std::string latestCode;
                double latestSecondsRemaining;
                totpPoller->GetLatest(latestCode, latestSecondsRemaining, totpPeriodSeconds);

                if (latestCode != currentCode)
                {
                    currentCode = latestCode;
                    RegenerateQr(currentCode, qrTempBuffer, qrCode);
                }

                secondsRemaining = latestSecondsRemaining;
            }
            else
            {
                // No response yet (first frame or a network hiccup): keep
                // showing the placeholder rather than blocking.
                secondsRemaining = 0.0;
            }
        }
        else
        {
            totalTime += io.DeltaTime;

            const int cycleIndex = (int)(totalTime / kCodeLifetimeSeconds);
            const double secondsIntoCycle = totalTime - cycleIndex * kCodeLifetimeSeconds;
            secondsRemaining = kCodeLifetimeSeconds - secondsIntoCycle;
            totpPeriodSeconds = kCodeLifetimeSeconds;

            if (cycleIndex != lastCycleIndex)
            {
                lastCycleIndex = cycleIndex;
                currentCode = GenerateAttendanceCode();
                RegenerateQr(currentCode, qrTempBuffer, qrCode);
            }
        }

        // Fullscreen, static kiosk window: no title bar, no resize/move handles, nothing clickable.
        ImGui::SetNextWindowPos(ImVec2(0, 0));
        ImGui::SetNextWindowSize(io.DisplaySize);

        ImGuiWindowFlags windowFlags =
            ImGuiWindowFlags_NoTitleBar |
            ImGuiWindowFlags_NoResize |
            ImGuiWindowFlags_NoMove |
            ImGuiWindowFlags_NoCollapse |
            ImGuiWindowFlags_NoSavedSettings |
            ImGuiWindowFlags_NoScrollbar;

        ImGui::Begin("Attendance", nullptr, windowFlags);

        // Header bar: app name on the left, version + room on the right.
        {
            char rightLabel[96];
            snprintf(rightLabel, sizeof(rightLabel), "v%s    Room %s", kAppVersion, headerRoom.c_str());

            ImGui::TextUnformatted("Attendance Tool");
            ImGui::SameLine();

            float rightWidth = ImGui::CalcTextSize(rightLabel).x;
            ImGui::SetCursorPosX(ImGui::GetContentRegionMax().x - rightWidth);
            ImGui::TextDisabled("%s", rightLabel);
        }
        ImGui::Separator();
        ImGui::Spacing();

        const float panelHeight = ImGui::GetContentRegionAvail().y;

        // Left panel: today's schedule.
        ImGui::BeginChild("SchedulePanel", ImVec2(ImGui::GetContentRegionAvail().x * 0.55f, panelHeight), true, ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoInputs);

        ImGui::TextUnformatted("Today's Schedule");
        ImGui::Separator();
        ImGui::Spacing();

        for (const ScheduleEntry& item : schedule)
        {
            ImGui::TextUnformatted(item.time.c_str());
            ImGui::SameLine(140.0f);
            ImGui::TextWrapped("%s", item.course.c_str());

            ImGui::Indent(140.0f);
            ImGui::TextDisabled("%s", item.room.c_str());
            ImGui::Unindent(140.0f);

            ImGui::Spacing();
        }

        ImGui::EndChild();

        ImGui::SameLine();

        // Right panel: rotating check-in QR code, code text, and countdown bar.
        ImGui::BeginChild("CheckInPanel", ImVec2(0, panelHeight), true, ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoInputs);

        ImGui::TextUnformatted("Scan to Check In");
        ImGui::SameLine();
        if (useRemoteTotp)
            ImGui::TextDisabled("(live)");
        else
            ImGui::TextDisabled("(offline demo)");
        ImGui::Separator();
        ImGui::Spacing();

        const float moduleSize = 4.0f;
        const int qrSize = qrcodegen_getSize(qrCode);
        const float qrPixelSize = (float)(qrSize + 8) * moduleSize;

        const float availWidth = ImGui::GetContentRegionAvail().x;
        const float qrOffsetX = (availWidth - qrPixelSize) * 0.5f;
        if (qrOffsetX > 0.0f)
            ImGui::SetCursorPosX(ImGui::GetCursorPosX() + qrOffsetX);

        ImVec2 qrScreenPos = ImGui::GetCursorScreenPos();
        DrawQrCode(ImGui::GetWindowDrawList(), qrScreenPos, qrCode, moduleSize);
        ImGui::Dummy(ImVec2(qrPixelSize, qrPixelSize));

        ImGui::Spacing();

        // Centered code text.
        {
            float textWidth = ImGui::CalcTextSize(currentCode.c_str()).x;
            float offsetX = (availWidth - textWidth) * 0.5f;
            if (offsetX > 0.0f)
                ImGui::SetCursorPosX(ImGui::GetCursorPosX() + offsetX);
            ImGui::TextUnformatted(currentCode.c_str());
        }

        ImGui::Spacing();
        ImGui::Spacing();

        // Countdown bar: full when the code just rotated, empty at 0.
        char overlay[32];
        snprintf(overlay, sizeof(overlay), "%d s", (int)ceil(secondsRemaining));
        float fraction = totpPeriodSeconds > 0.0 ? (float)(secondsRemaining / totpPeriodSeconds) : 0.0f;
        if (fraction < 0.0f) fraction = 0.0f;
        if (fraction > 1.0f) fraction = 1.0f;
        ImGui::ProgressBar(fraction, ImVec2(-FLT_MIN, 0.0f), overlay);

        ImGui::EndChild();

        ImGui::End();

        // Render
        ImGui::Render();

        int width;
        int height;

        SDL_GL_GetDrawableSize(window, &width, &height);

        glViewport(0, 0, width, height);

        glClearColor(
            0.05f,
            0.05f,
            0.08f,
            1.0f
        );

        glClear(GL_COLOR_BUFFER_BIT);

        ImGui_ImplOpenGL3_RenderDrawData(
            ImGui::GetDrawData()
        );

        SDL_GL_SwapWindow(window);
    }

    // Cleanup
    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplSDL2_Shutdown();
    ImGui::DestroyContext();

    SDL_GL_DeleteContext(gl_context);
    SDL_DestroyWindow(window);
    SDL_Quit();

    HttpGlobalCleanup();

    return 0;
}
